FROM python:3.6.3
MAINTAINER Konstantinos Bairaktaris "ikijob@gmail.com"
# RUN apt-get update -y
# RUN apt-get install -y python-pip python-dev build-essential
COPY ./web/requirements.txt /
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt
COPY ./web /app
WORKDIR /app
ENV FLASK_APP runserver.py
CMD flask run --with-threads -h 0.0.0.0 -p 5000
